version: 2
jobs:
  build_aar:
    docker:
      - image: blixtwallet/blixtwallet:latest
    steps:
      - run: go get golang.org/x/tools/go/packages
      - run: go get golang.org/x/tools/cmd/goimports
      - run: go get golang.org/x/mobile/cmd/gomobile
      - run: gomobile init
      - run: GO111MODULE=on go get github.com/golang/protobuf/protoc-gen-go@v1.3.2
      - run: GO111MODULE=on go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v1.14.3
      - run: GO111MODULE=on go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@v1.14.3
      - run: GO111MODULE=on go get -u -v github.com/lightninglabs/falafel
      - run: go get -d github.com/lightningnetwork/lnd
      - run: cd $GOPATH/src/github.com/lightningnetwork/lnd
      - run: cd $GOPATH/src/github.com/lightningnetwork/lnd && git checkout v0.12.0-beta && sed -i 's/use_prefix="0"/use_prefix="1"/g' mobile/gen_bindings.sh && make android tags="routerrpc walletrpc signrpc invoicesrpc"
      - persist_to_workspace:
          root: /go/src/github.com/lightningnetwork/lnd
          paths:
            - mobile/build/android/Lndmobile.aar
  build_blixt:
    docker:
      - image: blixtwallet/blixtwallet:latest
    steps:
      - attach_workspace:
          at: /go/src/github.com/lightningnetwork/lnd
      - checkout
      - run: cp /go/src/github.com/lightningnetwork/lnd/mobile/build/android/Lndmobile.aar android/lndmobile
      - run: yarn
      - run: git submodule update --init
      - run: yarn build-tor-lib
      - run: yarn gen-proto
      # - run: yarn test
      # Compile a bundled dev build https://stackoverflow.com/a/56520746
      # - run: ./node_modules/.bin/react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      # - run: cd android && ./gradlew assembleChainmainnetNormalDebug && ./gradlew assembleChaintestnetNormalDebug
      # - store_artifacts:
      #     path: android/app/build/outputs
workflows:
  version: 2
  build:
    jobs:
      - build_aar
      # - build_blixt:
      #     requires:
      #       - build_aar
