version: 2
jobs:
  build_aar:
    docker:
      - image: blixtwallet/blixtwallet:latest
    steps:
      - run: go get golang.org/x/mobile/cmd/gomobile
      - run: go get golang.org/x/tools/go/packages
      - run: gomobile init
      - run: go get -u github.com/halseth/falafel
      - run: go get -d github.com/lightningnetwork/lnd
      - run: cd $GOPATH/src/github.com/lightningnetwork/lnd && make android
      - persist_to_workspace:
          root: /go/src/github.com/lightningnetwork/lnd
          paths:
            - mobile/build/android/Lndmobile.aar
  build_blixt:
    docker:
      - image: blixtwallet/blixtwallet:latest
    steps:
      - attach_workspace:
          at: /go/src/github.com/lightningnetwork/lnd
      - checkout
      - run: cp /go/src/github.com/lightningnetwork/lnd/mobile/build/android/Lndmobile.aar android/lndmobile
      - run: yarn
      - run: yarn gen-proto
      # Compile a bundled dev build https://stackoverflow.com/a/56520746
      - run: ./node_modules/.bin/react-native bundle --platform android --dev false --entry-file index.ts --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      - run: cd android && ./gradlew assembleDebug
      - store_artifacts:
          path: android/app/build/outputs
workflows:
  version: 2
  build:
    jobs:
      - build_aar
      - build_blixt:
          requires:
            - build_aar
